apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exam-review-api
  namespace: exam-review
spec:
  selector:
    matchLabels:
      app: exam-review-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
